# Generated by Django 5.2.3 on 2025-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('insurance_provider', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=100)),
            ],
        ),
    ]
