# Generated by Django 5.2.3 on 2025-06-22 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_toothrecord_crownrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.patient')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.toothrecord')),
            ],
        ),
    ]
