# Generated by Django 5.2.3 on 2025-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_treatmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='quadrant',
            field=models.CharField(blank=True, choices=[('UR', 'Upper Right'), ('UL', 'Upper Left'), ('LR', 'Lower Right'), ('LL', 'Lower Left')], max_length=2, null=True),
        ),
    ]
