# Generated by Django 5.2.3 on 2025-06-26 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_treatmentrecord_quadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crownrecommendation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='tooth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claims.toothrecord'),
        ),
    ]
