# Generated by Django 5.2.3 on 2025-07-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_treatmentrecord_status_treatmentrecord_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientXRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.patient')),
            ],
        ),
    ]
