# Generated by Django 5.2.3 on 2025-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_patientxray'),
    ]

    operations = [
        migrations.AddField(
            model_name='crownrecommendation',
            name='claim_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
