# Generated by Django 5.2.3 on 2025-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_crownrecommendation_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='claim_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
